schema_version = 1
name = "QIDIStudio"
repository = "https://github.com/QIDITECH/QIDIStudio.git"
family = "bambu"
executable = "qidi-studio"
architectures = ["x86-64"]

[capabilities]
binary = true
config_dump = true
thumbnail = true

[patches]
shared = ["cli-thumbnail-glew-glx"]

[ci.binary]
enabled = false
publish = false
release = "none"
nightly = true

[ci.config]
enabled = false
publish = false
release = "none"
nightly = true
