schema_version = 1
name = "SnapmakerOrca"
repository = "https://github.com/Snapmaker/OrcaSlicer.git"
family = "orca"
executable = "snapmaker-orca"
architectures = ["x86-64"]

[capabilities]
binary = true
config_dump = false
thumbnail = true

[patches]
shared = [
    "cli-thumbnail-glew-glx",
    "cli-thumbnail-orca-legacy",
]

[ci.binary]
enabled = true
publish = true
release = "latest"
nightly = true

[ci.config]
enabled = false
publish = false
release = "none"
nightly = false
