schema_version = 1
name = "SnapmakerOrca"
repository = "https://github.com/Snapmaker/OrcaSlicer.git"
family = "orca"
executable = "snapmaker-orca"
architectures = ["x86-64"]

[capabilities]
binary = true
config_dump = true
thumbnail = true

[patches]
shared = [
    "dump-configs-orca-legacy",
    "glfw-x11-orca-legacy",
    "glew-glx-orca-legacy",
    "cli-thumbnail-glew-glx",
    "cli-thumbnail-orca-legacy",
]

[ci.binary]
enabled = true
publish = true
release = "latest"
nightly = true

[ci.config]
enabled = true
publish = true
release = "latest"
nightly = true
