schema_version = 1
name = "SuperSlicer"
repository = "https://github.com/supermerill/SuperSlicer.git"
default_ref = "2.5.59.13"
expected_commit = "e2eef1da2d395d92ad0875c478bca67c0bb8ec9f"
family = "prusa"
executable = "superslicer"
architectures = ["x86-64"]

[capabilities]
binary = true
config_dump = true
thumbnail = false

[ci.binary]
enabled = true
publish = true
release = "tag:2.5.59.13"
nightly = false

[ci.config]
enabled = false
publish = false
release = "tag:2.5.59.13"
nightly = true
gui = true
