schema_version = 1
name = "SuperSlicer"
repository = "https://github.com/supermerill/SuperSlicer.git"
family = "prusa"
executable = "superslicer"
architectures = ["x86-64"]

[capabilities]
binary = true
config_dump = true
thumbnail = false

[ci.binary]
enabled = true
publish = true
release = "latest"
nightly = false

[ci.config]
enabled = false
publish = false
release = "none"
nightly = true
gui = true
