schema_version = 1
name = "OrcaSlicer"
repository = "https://github.com/OrcaSlicer/OrcaSlicer.git"
family = "orca"
executable = "orca-slicer"
architectures = ["x86-64", "arm64"]

[capabilities]
binary = true
config_dump = true
thumbnail = true

[patches]
shared = ["cli-thumbnail-orca-opengl-version"]

[patches.binary_ref_aliases]
"v2.4.1" = "v2.4.2"

[ci.binary]
enabled = true
publish = true
release = "latest"
nightly = true

[ci.config]
enabled = true
publish = true
release = "latest"
nightly = true
